"""add planning foundation tables

Revision ID: 18fb9ccb3924
Revises: 3b9ee03aa169
Create Date: 2026-03-19 11:44:14.260103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18fb9ccb3924'
down_revision: Union[str, Sequence[str], None] = '3b9ee03aa169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_focus_snapshot', sa.String(), nullable=True),
    sa.Column('weekly_hours_snapshot', sa.Integer(), nullable=False),
    sa.Column('source_learning_state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_plans_current_focus_snapshot'), 'learning_plans', ['current_focus_snapshot'], unique=False)
    op.create_index(op.f('ix_learning_plans_goal'), 'learning_plans', ['goal'], unique=False)
    op.create_index(op.f('ix_learning_plans_id'), 'learning_plans', ['id'], unique=False)
    op.create_index(op.f('ix_learning_plans_status'), 'learning_plans', ['status'], unique=False)
    op.create_index(op.f('ix_learning_plans_user_id'), 'learning_plans', ['user_id'], unique=False)
    op.create_table('schedule_queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_schedule_queue_user_course')
    )
    op.create_index(op.f('ix_schedule_queue_items_course_id'), 'schedule_queue_items', ['course_id'], unique=False)
    op.create_index(op.f('ix_schedule_queue_items_id'), 'schedule_queue_items', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_queue_items_status'), 'schedule_queue_items', ['status'], unique=False)
    op.create_index(op.f('ix_schedule_queue_items_user_id'), 'schedule_queue_items', ['user_id'], unique=False)
    op.create_table('learning_plan_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'course_id', name='uq_learning_plan_course')
    )
    op.create_index(op.f('ix_learning_plan_courses_course_id'), 'learning_plan_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_plan_courses_id'), 'learning_plan_courses', ['id'], unique=False)
    op.create_index(op.f('ix_learning_plan_courses_plan_id'), 'learning_plan_courses', ['plan_id'], unique=False)
    op.create_index(op.f('ix_learning_plan_courses_status'), 'learning_plan_courses', ['status'], unique=False)
    op.create_table('scheduling_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('preferred_time_window', sa.String(), nullable=False),
    sa.Column('pace_mode', sa.String(), nullable=False),
    sa.Column('preferred_study_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_daily_minutes', sa.Integer(), nullable=False),
    sa.Column('session_cap_minutes', sa.Integer(), nullable=False),
    sa.Column('temporary_note', sa.Text(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_preferences_id'), 'scheduling_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_scheduling_preferences_pace_mode'), 'scheduling_preferences', ['pace_mode'], unique=False)
    op.create_index(op.f('ix_scheduling_preferences_plan_id'), 'scheduling_preferences', ['plan_id'], unique=True)
    op.create_index(op.f('ix_scheduling_preferences_preferred_time_window'), 'scheduling_preferences', ['preferred_time_window'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduling_preferences_preferred_time_window'), table_name='scheduling_preferences')
    op.drop_index(op.f('ix_scheduling_preferences_plan_id'), table_name='scheduling_preferences')
    op.drop_index(op.f('ix_scheduling_preferences_pace_mode'), table_name='scheduling_preferences')
    op.drop_index(op.f('ix_scheduling_preferences_id'), table_name='scheduling_preferences')
    op.drop_table('scheduling_preferences')
    op.drop_index(op.f('ix_learning_plan_courses_status'), table_name='learning_plan_courses')
    op.drop_index(op.f('ix_learning_plan_courses_plan_id'), table_name='learning_plan_courses')
    op.drop_index(op.f('ix_learning_plan_courses_id'), table_name='learning_plan_courses')
    op.drop_index(op.f('ix_learning_plan_courses_course_id'), table_name='learning_plan_courses')
    op.drop_table('learning_plan_courses')
    op.drop_index(op.f('ix_schedule_queue_items_user_id'), table_name='schedule_queue_items')
    op.drop_index(op.f('ix_schedule_queue_items_status'), table_name='schedule_queue_items')
    op.drop_index(op.f('ix_schedule_queue_items_id'), table_name='schedule_queue_items')
    op.drop_index(op.f('ix_schedule_queue_items_course_id'), table_name='schedule_queue_items')
    op.drop_table('schedule_queue_items')
    op.drop_index(op.f('ix_learning_plans_user_id'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_status'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_id'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_goal'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_current_focus_snapshot'), table_name='learning_plans')
    op.drop_table('learning_plans')
    # ### end Alembic commands ###
