"""add course structure foundation

Revision ID: 1ccd946f712c
Revises: 18fb9ccb3924
Create Date: 2026-03-19 12:56:23.036868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ccd946f712c'
down_revision: Union[str, Sequence[str], None] = '18fb9ccb3924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('structure_type', sa.String(), nullable=False),
    sa.Column('build_status', sa.String(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('structure_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('build_notes', sa.Text(), nullable=True),
    sa.Column('last_built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_structures_build_status'), 'course_structures', ['build_status'], unique=False)
    op.create_index(op.f('ix_course_structures_content_type'), 'course_structures', ['content_type'], unique=False)
    op.create_index(op.f('ix_course_structures_course_id'), 'course_structures', ['course_id'], unique=True)
    op.create_index(op.f('ix_course_structures_id'), 'course_structures', ['id'], unique=False)
    op.create_index(op.f('ix_course_structures_source'), 'course_structures', ['source'], unique=False)
    op.create_index(op.f('ix_course_structures_structure_type'), 'course_structures', ['structure_type'], unique=False)
    op.create_table('course_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_structure_id', sa.Integer(), nullable=False),
    sa.Column('external_unit_id', sa.String(), nullable=True),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_order_index', sa.Integer(), nullable=False),
    sa.Column('raw_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('start_second', sa.Integer(), nullable=True),
    sa.Column('end_second', sa.Integer(), nullable=True),
    sa.Column('practical_signal', sa.String(), nullable=False),
    sa.Column('load_signal', sa.String(), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_structure_id'], ['course_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_structure_id', 'source_order_index', name='uq_course_units_structure_order')
    )
    op.create_index(op.f('ix_course_units_course_structure_id'), 'course_units', ['course_structure_id'], unique=False)
    op.create_index(op.f('ix_course_units_external_unit_id'), 'course_units', ['external_unit_id'], unique=False)
    op.create_index(op.f('ix_course_units_id'), 'course_units', ['id'], unique=False)
    op.create_index(op.f('ix_course_units_load_signal'), 'course_units', ['load_signal'], unique=False)
    op.create_index(op.f('ix_course_units_practical_signal'), 'course_units', ['practical_signal'], unique=False)
    op.create_index(op.f('ix_course_units_unit_type'), 'course_units', ['unit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_units_unit_type'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_practical_signal'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_load_signal'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_id'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_external_unit_id'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_course_structure_id'), table_name='course_units')
    op.drop_table('course_units')
    op.drop_index(op.f('ix_course_structures_structure_type'), table_name='course_structures')
    op.drop_index(op.f('ix_course_structures_source'), table_name='course_structures')
    op.drop_index(op.f('ix_course_structures_id'), table_name='course_structures')
    op.drop_index(op.f('ix_course_structures_course_id'), table_name='course_structures')
    op.drop_index(op.f('ix_course_structures_content_type'), table_name='course_structures')
    op.drop_index(op.f('ix_course_structures_build_status'), table_name='course_structures')
    op.drop_table('course_structures')
    # ### end Alembic commands ###
