"""create youtube content pipeline tables

Revision ID: 3628d3195f0f
Revises: 2412f4a22f8b
Create Date: 2026-03-18 12:56:58.576849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3628d3195f0f'
down_revision: Union[str, Sequence[str], None] = '2412f4a22f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_ingestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_ingestions_id'), 'course_ingestions', ['id'], unique=False)
    op.create_index(op.f('ix_course_ingestions_query'), 'course_ingestions', ['query'], unique=False)
    op.create_index(op.f('ix_course_ingestions_source'), 'course_ingestions', ['source'], unique=False)
    op.create_index(op.f('ix_course_ingestions_status'), 'course_ingestions', ['status'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_channel_title'), 'courses', ['channel_title'], unique=False)
    op.create_index(op.f('ix_courses_content_type'), 'courses', ['content_type'], unique=False)
    op.create_index(op.f('ix_courses_external_id'), 'courses', ['external_id'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_language'), 'courses', ['language'], unique=False)
    op.create_index(op.f('ix_courses_provider'), 'courses', ['provider'], unique=False)
    op.create_index(op.f('ix_courses_source'), 'courses', ['source'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('raw_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('normalized_title', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_id'], ['course_ingestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_courses_channel_title'), 'raw_courses', ['channel_title'], unique=False)
    op.create_index(op.f('ix_raw_courses_content_type'), 'raw_courses', ['content_type'], unique=False)
    op.create_index(op.f('ix_raw_courses_external_id'), 'raw_courses', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_courses_id'), 'raw_courses', ['id'], unique=False)
    op.create_index(op.f('ix_raw_courses_ingestion_id'), 'raw_courses', ['ingestion_id'], unique=False)
    op.create_index(op.f('ix_raw_courses_is_accepted'), 'raw_courses', ['is_accepted'], unique=False)
    op.create_index(op.f('ix_raw_courses_is_processed'), 'raw_courses', ['is_processed'], unique=False)
    op.create_index(op.f('ix_raw_courses_language'), 'raw_courses', ['language'], unique=False)
    op.create_index(op.f('ix_raw_courses_normalized_title'), 'raw_courses', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_raw_courses_source'), 'raw_courses', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_courses_source'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_normalized_title'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_language'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_is_processed'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_is_accepted'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_ingestion_id'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_id'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_external_id'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_content_type'), table_name='raw_courses')
    op.drop_index(op.f('ix_raw_courses_channel_title'), table_name='raw_courses')
    op.drop_table('raw_courses')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_source'), table_name='courses')
    op.drop_index(op.f('ix_courses_provider'), table_name='courses')
    op.drop_index(op.f('ix_courses_language'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_external_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_content_type'), table_name='courses')
    op.drop_index(op.f('ix_courses_channel_title'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_course_ingestions_status'), table_name='course_ingestions')
    op.drop_index(op.f('ix_course_ingestions_source'), table_name='course_ingestions')
    op.drop_index(op.f('ix_course_ingestions_query'), table_name='course_ingestions')
    op.drop_index(op.f('ix_course_ingestions_id'), table_name='course_ingestions')
    op.drop_table('course_ingestions')
    # ### end Alembic commands ###
