"""add user profiles

Revision ID: 686e8f0e965f
Revises: df0e5a2948f6
Create Date: 2026-03-18 21:28:03.001538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686e8f0e965f'
down_revision: Union[str, Sequence[str], None] = 'df0e5a2948f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('background_track', sa.String(), nullable=False),
    sa.Column('employment_status', sa.String(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('education_major', sa.String(), nullable=True),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_background_track'), 'user_profiles', ['background_track'], unique=False)
    op.create_index(op.f('ix_user_profiles_employment_status'), 'user_profiles', ['employment_status'], unique=False)
    op.create_index(op.f('ix_user_profiles_goal'), 'user_profiles', ['goal'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_preferred_language'), 'user_profiles', ['preferred_language'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_preferred_language'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_goal'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_employment_status'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_background_track'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
