"""add learning plan items and schedule generation foundation

Revision ID: 85292fdfecc2
Revises: 1ccd946f712c
Create Date: 2026-03-19 13:13:45.717499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85292fdfecc2'
down_revision: Union[str, Sequence[str], None] = '1ccd946f712c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('plan_course_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_unit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('schedule_order_index', sa.Integer(), nullable=False),
    sa.Column('source_order_index', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('time_window', sa.String(), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('segment_start_second', sa.Integer(), nullable=True),
    sa.Column('segment_end_second', sa.Integer(), nullable=True),
    sa.Column('practical_signal', sa.String(), nullable=False),
    sa.Column('load_signal', sa.String(), nullable=False),
    sa.Column('item_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['course_unit_id'], ['course_units.id'], ),
    sa.ForeignKeyConstraint(['plan_course_id'], ['learning_plan_courses.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'plan_course_id', 'course_unit_id', 'segment_index', name='uq_plan_item_unit_segment')
    )
    op.create_index(op.f('ix_learning_plan_items_course_id'), 'learning_plan_items', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_course_unit_id'), 'learning_plan_items', ['course_unit_id'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_id'), 'learning_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_item_type'), 'learning_plan_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_load_signal'), 'learning_plan_items', ['load_signal'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_plan_course_id'), 'learning_plan_items', ['plan_course_id'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_plan_id'), 'learning_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_practical_signal'), 'learning_plan_items', ['practical_signal'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_schedule_order_index'), 'learning_plan_items', ['schedule_order_index'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_scheduled_date'), 'learning_plan_items', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_status'), 'learning_plan_items', ['status'], unique=False)
    op.create_index(op.f('ix_learning_plan_items_time_window'), 'learning_plan_items', ['time_window'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_plan_items_time_window'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_status'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_scheduled_date'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_schedule_order_index'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_practical_signal'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_plan_id'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_plan_course_id'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_load_signal'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_item_type'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_id'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_course_unit_id'), table_name='learning_plan_items')
    op.drop_index(op.f('ix_learning_plan_items_course_id'), table_name='learning_plan_items')
    op.drop_table('learning_plan_items')
    # ### end Alembic commands ###
