"""add user learning states

Revision ID: 8f94c828d81b
Revises: 4111e1689d8c
Create Date: 2026-03-18 21:53:15.796805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f94c828d81b'
down_revision: Union[str, Sequence[str], None] = '4111e1689d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_learning_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dominant_interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('emerging_interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_focus', sa.String(), nullable=True),
    sa.Column('preferred_content_type', sa.String(), nullable=True),
    sa.Column('preferred_course_length', sa.String(), nullable=True),
    sa.Column('effective_preferred_language', sa.String(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('source_profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_event_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_learning_states_current_focus'), 'user_learning_states', ['current_focus'], unique=False)
    op.create_index(op.f('ix_user_learning_states_effective_preferred_language'), 'user_learning_states', ['effective_preferred_language'], unique=False)
    op.create_index(op.f('ix_user_learning_states_id'), 'user_learning_states', ['id'], unique=False)
    op.create_index(op.f('ix_user_learning_states_preferred_content_type'), 'user_learning_states', ['preferred_content_type'], unique=False)
    op.create_index(op.f('ix_user_learning_states_preferred_course_length'), 'user_learning_states', ['preferred_course_length'], unique=False)
    op.create_index(op.f('ix_user_learning_states_user_id'), 'user_learning_states', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_learning_states_user_id'), table_name='user_learning_states')
    op.drop_index(op.f('ix_user_learning_states_preferred_course_length'), table_name='user_learning_states')
    op.drop_index(op.f('ix_user_learning_states_preferred_content_type'), table_name='user_learning_states')
    op.drop_index(op.f('ix_user_learning_states_id'), table_name='user_learning_states')
    op.drop_index(op.f('ix_user_learning_states_effective_preferred_language'), table_name='user_learning_states')
    op.drop_index(op.f('ix_user_learning_states_current_focus'), table_name='user_learning_states')
    op.drop_table('user_learning_states')
    # ### end Alembic commands ###
